name: "Create ECR Image on New tag"

on:
  push:
    tags:
      - "*"

env:
  AWS_REGION: us-west-2
  CODEBUILD_PROJECT: fullstack-app-db-migration
  BUILDSPEC_PATH: ./buildspec.yaml
  ECR_REPOSITORY: fullstack-app/backend
  ECS_TASK_DEF: be-task
  ECS_CONTAINER: be-container
  ECS_SERVICE: backend
  ECS_CLUSTER: fullstack-app

jobs:
  redeploy-backend-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run codebuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.CODEBUILD_PROJECT }}
          buildspec-override: ${{ env.BUILDSPEC_PATH }}

      - name: Login on AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build, tag, and push docker image to Amazon ECR
        id: image-push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image_uri=$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download current task definition JSON
        run: aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEF }} --query taskDefinition > task-definition.json

      - name: Render task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          image: ${{steps.image-push.outputs.image_uri}}
          container-name: ${{ env.ECS_CONTAINER }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Notify unsuccessful deploy status
        uses: rtCamp/action-slack-notify@v2
        if: ${{ always() && failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "DEPLOYMENT STOPPED"
          SLACK_MESSAGE: "Backend service was deployed with errors"

      - name: Check if rollback occured
        if: success()
        id: check-rollback
        run: |
          CURRENT_TD=$(aws ecs describe-services --cluster ${{env.ECS_CLUSTER}} --services ${{env.ECS_SERVICE}} --query "services[0].taskDefinition")
          CURRENT_IMAGE=$(aws ecs describe-task-definition --task-definition $CURRENT_TD --query "taskDefinition.containerDefinitions[0].image")

          if [ ${{steps.image-push.outputs.image_uri}} == $CURRENT_IMAGE ]
          then
            echo "is_rollback=0" >> $GITHUB_OUTPUT
          else
            echo "is_rollback=1" >> $GITHUB_OUTPUT
          fi

      - name: Notify successful deploy status
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() && steps.check-rollback.outputs.is_rollback == '0' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "DEPLOYMENT SUCCESSFULL"
          SLACK_MESSAGE: "Backend service was deployed successfully"

      - name: Notify successful rollback deploy status
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() && steps.check-rollback.outputs.is_rollback == '1' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "DEPLOYMENT ROLLBACK"
          SLACK_MESSAGE: "Backend service was rollbacked successfully"
